apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: cache
status:
  loadBalancer: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cache-claim0
  name: cache-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: cache
    spec:
      containers:
      - image: busybox
        name: cache
        resources: {}
        volumeMounts:
        - mountPath: /app/node_modules
          name: cache-claim0
      restartPolicy: Always
      volumes:
      - name: cache-claim0
        persistentVolumeClaim:
          claimName: cache-claim0
status: {}
