version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    volumes:
      - '.:/app/'
  cache:
    image: busybox
    volumes:
      - /app/node_modules
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRESS_PASSWORD}'
      POSTGRES_DB: onetimeurl
    ports:
      - '5432:5432'
