version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    links:
      - database
    volumes:
      - '.:/app/'
  data:
    image: busybox
    volumes:
      - /app/node_modules
  database:
    image: 'postgres:alpine'
